Vagrant.configure("2") do |config|
    config.vm.define "postgres" do |postgres|
      postgres.vm.box = "bento/ubuntu-20.04"
      postgres.vm.network "private_network", type: "dhcp"
      postgres.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
      end
      postgres.vm.provision "shell", inline: <<-SHELL
        echo 'Step 1: Instalando Docker and Docker Compose'
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose
        sudo usermod -aG docker vagrant
        sudo systemctl enable docker
        sudo systemctl start docker
      SHELL
    end
  
    config.vm.define "mongodb" do |mongodb|
        mongodb.vm.box = "bento/ubuntu-20.04"
        mongodb.vm.network "private_network", type: "dhcp"
        mongodb.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
      end
      mongodb.vm.provision "shell", inline: <<-SHELL
        echo 'Step 1: Instalando Docker and Docker Compose'
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose
        sudo usermod -aG docker vagrant
        sudo systemctl enable docker
        sudo systemctl start docker
      SHELL
    end
  end