secrets = {}
File.readlines('secrets.conf').each do |line|
  key, value = line.split('=')
  secrets[key.strip] = value.strip.delete('"')
end

db_password = secrets['db_password']
admin_password = secrets['admin_password']

Vagrant.configure("2") do |config|
  config.vm.define "database" do |database|
    database.vm.box = "bento/ubuntu-20.04"
    database.vm.network "private_network", type: "dhcp"
    database.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

    # Instalando o Docker
    database.vm.provision "shell", inline: "echo 'Step 0: Instalando o Docker'"
    database.vm.provision "shell", path: "../Scripts/install_docker.sh"

    # Instalando e subindo o Postgres
    database.vm.provision "shell", inline: <<-SHELL
      echo 'Step 1: Configurando o Postgres'
      sudo docker run --name postgres -e POSTGRES_PASSWORD=#{db_password} -d postgres
    SHELL

    # Instalando e subindo o MongoDB
    database.vm.provision "shell", inline: <<-SHELL
      echo 'Step 2: Instalando o MongoDB'
      sudo docker run -d --name mongodb -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=#{admin_password} mongo
    SHELL
  end
end